#! /bin/bash
# /etc/pm/sleep.d/50alsa : Restart alsa after sleeping
case "$!" in
    hibernate|suspend)
        #stopping is not required
        ;;
    thaw|resume)
        #Reload alsa
        /sbin/alsa force-reload
        ;;
    *) exit $NA
        ;;
esac
