#Maico timmerman alias ~/.bash_aliases file for user
#User specific aliases and functions

# alias to edit all aliases and automatically load them in
# after editting.
alias aliases="vim ~/.bash_aliases; source ~/.bash_aliases"

#cd aliases
alias cduva="cd ~/Dropbox/uva/"
alias cdcv="cd ~/Dropbox/Curriculum\ Vitea"
alias cdos="cd ~/Dropbox/uva/os"
alias cdaft="cd ~/Dropbox/uva/aft/"
alias cdata="cd /media/maico/DATA/"
alias cdisam="cd ~/Dropbox/uva/os/assignments/assignment3"
alias cdreview="cd ~/Dropbox/uva/tutoraat/blok5/review"
alias hacker="cd /home/maico/Dropbox/hacker.org"

# More aliases!
alias ls="ls -h --color=auto"
alias clearl="clear;ls"
alias xclip="xclip -selection clipboard"
alias poweroff="sudo poweroff"
alias die="sudo poweroff"
alias reboot="sudo reboot"
alias screensaver="cmatrix -saxb -u 2"
alias gitpush="git push origin master"
alias gitcommit="git commit -a"
alias gitcp="git commit .;git push"
alias html="google-chrome"
alias uvavpn='sudo /usr/local/nc/ncsvc -h uvavpn.uva.nl -u 10542590 -r users -f /usr/local/nc/certificaat-uvavpn.der'
alias androidstudio='/home/maico/Downloads/android-studio/bin/studio.sh'
