#Maico timmerman alias ~/.bash_aliases file for user
#User specific aliases and functions

#cd aliases
alias cduva="cd ~/Dropbox/uva/"
alias cdcv="cd ~/Dropbox/Curriculum\ Vitea"
alias cdos="cd ~/Dropbox/uva/os"
alias cdaft="cd ~/Dropbox/uva/aft/"
alias cdata="cd /media/maico/DATA/"
alias cdscheduling="cd ~/Dropbox/uva/os/assignments/assignment2/linux-64"
alias hacker="cd /home/maico/Dropbox/hacker.org"

alias ls="ls -h --color=auto"
alias clearl="clear;ll"
alias xclip="xclip -selection clipboard"
alias poweroff="sudo poweroff"
alias die="sudo poweroff"
alias reboot="sudo reboot"
alias screensaver="cmatrix -saxb -u 2"
alias gitpush="git push origin master"
alias gitcommit="git commit -a"
alias gitcp="git commit .;git push"
alias html="google-chrome"
alias uvavpn='sudo /usr/local/nc/ncsvc -h uvavpn.uva.nl -u 10542590 -r users -f /usr/local/nc/certificaat-uvavpn.der'
alias python="python3.3"
